---
- name: Create ramdisk directory
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0755
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  loop: "{{ ramdisk }}"

- name: Create /etc/fstab entry and mount the ramdisk
  mount:
    path: "{{ item.path }}"
    src: tmpfs
    fstype: tmpfs
    state: mounted
    opts: "{{ item.mount_options }}"
  loop: "{{ ramdisk }}"
...
